### ISSUE TITLE
Visibility in Read Mode

### ISSUE THREAD

**Issue by eb2ai** [christianwannerstedt/obsidian-key-value-list#1]
I love what this does. It's simple and an effective way to format the display of information without requiring any additional markup.

However… it would be good for it to support the Read Mode as well.

**Comment by christianwannerstedt** [comment]
Thank you for your feedback! You're absolutely right, the plugin should definitely support read mode.. I'll try to fix it shortly.

**Comment by Cammagno** [comment]
> the plugin should definitely support read mode

Yes, but please make it optional, I can think of cases in which one could prefer to have it working only in edit or view mode

**Comment by christianwannerstedt** [comment]
This is now fixed in the latest release ([1.0.0](https://github.com/christianwannerstedt/obsidian-key-value-list/releases/tag/1.0.0))

**Comment by eb2ai** [comment]
Thanks. Working good!

**Comment by eb2ai** [comment]
FYI... I am now seeing this in the console.
![image](https://github.com/christianwannerstedt/obsidian-key-value-list/assets/134644662/20d5a91e-5fe7-467d-8cc5-8c3e6ff975aa)

**Comment by christianwannerstedt** [comment]
Oh, I believe that error will go away in the latest release ([1.1.0](https://github.com/christianwannerstedt/obsidian-key-value-list/releases/tag/1.1.0)). Please let me know if that's not the case and I'll look into it.

**Comment by eb2ai** [comment]
![image](https://github.com/christianwannerstedt/obsidian-key-value-list/assets/134644662/5a2bada6-9ca2-40a9-9f1d-266f65e51a92)
Using the latest version and still getting a lot of the errors in the console.

**Comment by christianwannerstedt** [comment]
Hmm, that's very weird.. I'm having a really hard time to understand how that could happen in the version you're using, and I'm not able to reproduce the issue myself. And the [line](https://github.com/christianwannerstedt/obsidian-key-value-list/blob/main/src/key-value-list.ts#L203) referenced in the stacktrace doesn't make too much sense either, it rather seems like it's from an older/cached version..

1) Do you get this error for every file, or just when you're editing a specific one?
2) Does the error still occur if you *Reload* the app?

Thanks for helping me troubleshoot this.

**Comment by eb2ai** [comment]
I loaded it in a sandbox, and it does not error out. However, If I disable all plugins and switch to the default theme, it still happens.

Maybe it is a caching issue. I will continue to investigate.
